name: ðŸŽ‰ Release new version

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
      commit_hash:
        description: 'Commit to tag and release'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release_to_github:
    name: Release new version
    needs: [build_windows, build_linux]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          envFilePath: .github/variables/global.env
      
      - name: Download Linux Build
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.LINUX_ARTIFACT_NAME }}
          path: build-${{ env.LINUX_ARTIFACT_NAME }}
      
      - name: Generate Release Notes
        run: |
          pip3 install requests Jinja2 html2markdown
          python3 generate-release-body.py ${{ inputs.version }} > release_notes.md
      
      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
            artifactErrorsFailBuild: true
            artifacts: "build-${{ env.LINUX_ARTIFACT_NAME }}/*"
            name: v${{ inputs.version }}
            omitName: true
            bodyFile: release_notes.md
            makeLatest: true
            tag: ${{ inputs.version }}
            commit: ${{ inputs.commit_hash }}
  
  build_windows:
    # Creates a new release if there were changes detected in the previous job.
    # It will also upload the Burp Suite JAR file to the release.
    name: Build Windows
    secrets: inherit
    with:
      version: ${{ inputs.version }}
    uses: mmgordon82/BurpSuiteInstaller/.github/workflows/release-windows.yml@main
  
  build_linux:
    name: Build Linux
    secrets: inherit
    with:
      version: ${{ inputs.version }}
    uses: mmgordon82/BurpSuiteInstaller/.github/workflows/release-linux.yml@main